FROM python:3.12
LABEL key="talhak911"
WORKDIR /code

RUN pip install poetry
COPY . /code/
RUN poetry config virtualenvs.create false
RUN poetry install
EXPOSE 8000
CMD [ "poetry", "run", "uvicorn", "dev_con.main:app", "--host", "0.0.0.0", "--reload" ]