FROM python:3.12
LABEL key="talhak911"
WORKDIR /code

RUN pip install poetry
COPY ./pyproject.toml /code/
COPY ./dev_cont1 /code/dev_cont1/
RUN poetry config virtualenvs.create false
RUN poetry install
EXPOSE 8000
CMD [ "poetry", "run", "uvicorn", "dev_cont1.main:app", "--host", "0.0.0.0", "--reload" ]